# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1iDqRdKm_ZfwVD_7ZOV41yf2mejaIVx
"""

import streamlit as st

import random

def gen():
    return random.randint(10, 99)
st.title('Mi primerra aplicación de Streamlit')
st.header('!Hola, Streamlit!',key = gen())
st.write('Esto es una aplicación simple')
st.image('logo.png',key = gen())
if st.button('Presiona Aqui',key = gen()):
    st.write('Has presionado el botón')

input = st.text_input('Escribe algo',key = gen())
st.write('Escribiste:', input)

st.sidebar.title('Mi Primera barra lateral de Streamlit')
st.sidebar.header('!Hola, Barra Lateral!')
st.sidebar.write('Esto es una barra lateral')
st.sidebar.image('logo.png',key = gen())

if st.sidebar.button('Presiona Aqui',key = gen()):
    st.sidebar.write('Has presionado el botón')

input = st.sidebar.text_input('Escribe algo',key = gen())
st.sidebar.write('Escribiste:', input)
