# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I1iDqRdKm_ZfwVD_7ZOV41yf2mejaIVx
"""

import streamlit as st
st.title('Mi primerra aplicación de Streamlit')
st.header('!Hola, Streamlit!')
st.write('Esto es una aplicación simple')
st.image('logo.png')
if st.button('Presiona Aqui',key = '1'):
    st.write('Has presionado el botón')

input = st.text_input('Escribe algo')
st.write('Escribiste:', input)

st.sidebar.title('Mi Primera barra lateral de Streamlit')
st.sidebar.header('!Hola, Barra Lateral!')
st.sidebar.write('Esto es una barra lateral')
st.sidebar.image('logo.png')

if st.sidebar.button('Presiona Aqui',key = '2'):
    st.sidebar.write('Has presionado el botón')

input = st.sidebar.text_input('Escribe algo')
st.sidebar.write('Escribiste:', input)
